name: "bb8-embedder-assist-crossencoder"
max_batch_size: 32
input [
  {
    name: "queries"
    data_type: TYPE_STRING
    dims: 1
  }
]
input [
  {
    name: "passages"
    data_type: TYPE_STRING
    dims: 1
  }
]
output [
  {
    name: "similarity_scores"
    data_type: TYPE_STRING
    dims: -1
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
backend: "python"
